"""Tests for the head-pose (solvePnP) pipeline stage.

The mesh fed to solvePnP is generated by projecting the canonical 3D model with a
*known* pose, so the estimator is checked against ground truth rather than merely
"returned something".
"""

from __future__ import annotations

import logging
import queue
import threading

import cv2
import numpy as np
import pytest

from gaze_estimation.pipeline.schemas import MeshPacket
from gaze_estimation.pose.canonical_face import CANONICAL_3D_POINTS, LANDMARK_INDICES
from gaze_estimation.pose.head_pose import HeadPoseEstimator, resolve_solvepnp_flags

CAM = np.array([[640.0, 0.0, 320.0], [0.0, 640.0, 240.0], [0.0, 0.0, 1.0]], dtype=np.float64)
DIST = np.zeros(5, dtype=np.float64)
FRAME = np.zeros((480, 640, 3), dtype=np.uint8)


def _mesh_for_pose(rvec, tvec, cam=CAM, dist=DIST, n=468, landmark_indices=LANDMARK_INDICES):
    """Project the canonical face with *rvec*/*tvec* and embed it as a mesh."""
    # cv2 requires both vectors to be (3, 1) floating-point arrays.
    rot = np.asarray(rvec, dtype=np.float64).reshape(3, 1)
    trans = np.asarray(tvec, dtype=np.float64).reshape(3, 1)
    projected, _ = cv2.projectPoints(CANONICAL_3D_POINTS, rot, trans, cam, dist)
    mesh = np.full((n, 2), 100.0, dtype=np.float32)
    mesh[landmark_indices] = projected.reshape(-1, 2)
    return mesh


def _estimator(**kwargs):
    q_in: queue.Queue = queue.Queue()
    q_out: queue.Queue = queue.Queue()
    kwargs.setdefault("camera_matrix", CAM)
    kwargs.setdefault("dist_coeffs", DIST)
    return HeadPoseEstimator(q_in, q_out, threading.Event(), **kwargs), q_in, q_out


def _mesh_packet(mesh, confidence=0.9, **overrides):
    fields = dict(
        timestamp=1.0,
        frame=FRAME,
        face_bbox=(100, 100, 200, 200),
        mesh_468=mesh,
        iris_478=None,
        left_iris_center=(280.0, 240.0),
        right_iris_center=(360.0, 240.0),
        left_iris_radius=8.0,
        right_iris_radius=8.0,
        confidence=confidence,
    )
    fields.update(overrides)
    return MeshPacket(**fields)


# ── resolve_solvepnp_flags ────────────────────────────────────────────────────


def test_full_constant_name_resolves():
    assert resolve_solvepnp_flags("SOLVEPNP_EPNP") == cv2.SOLVEPNP_EPNP


def test_short_name_is_expanded():
    assert resolve_solvepnp_flags("EPNP") == cv2.SOLVEPNP_EPNP


def test_names_are_case_and_whitespace_insensitive():
    assert resolve_solvepnp_flags("  epnp  ") == cv2.SOLVEPNP_EPNP


@pytest.mark.parametrize(
    "name", ["SOLVEPNP_ITERATIVE", "SOLVEPNP_P3P", "SOLVEPNP_AP3P", "SOLVEPNP_SQPNP"]
)
def test_common_solvers_resolve(name):
    assert resolve_solvepnp_flags(name) == getattr(cv2, name)


def test_unknown_name_falls_back_and_warns(caplog):
    with caplog.at_level(logging.WARNING, logger="gaze_estimation.pose.head_pose"):
        flags = resolve_solvepnp_flags("SOLVEPNP_TYPO")

    assert flags == cv2.SOLVEPNP_ITERATIVE
    assert "Unknown solvepnp method" in caplog.text


# ── solvePnP round-trips ──────────────────────────────────────────────────────


def test_recovers_a_frontal_pose():
    rvec_true = np.zeros(3)
    tvec_true = np.array([0.0, 0.0, 600.0])
    estimator, _, _ = _estimator()

    pose = estimator._solve_pnp(_mesh_for_pose(rvec_true, tvec_true))

    assert pose is not None
    np.testing.assert_allclose(pose.tvec, tvec_true, atol=1.0)
    np.testing.assert_allclose(pose.euler_angles, np.zeros(3), atol=0.5)


def test_recovers_a_rotated_pose():
    rot_vector = np.array([0.15, 0.30, -0.10])
    tvec_true = np.array([10.0, -20.0, 550.0])
    r_true, _ = cv2.Rodrigues(rot_vector)
    estimator, _, _ = _estimator()

    pose = estimator._solve_pnp(_mesh_for_pose(rot_vector, tvec_true))

    assert pose is not None
    np.testing.assert_allclose(pose.rotation_matrix, r_true, atol=0.02)
    np.testing.assert_allclose(pose.tvec, tvec_true, atol=2.0)


def test_reported_euler_angles_match_the_rotation_matrix():
    from gaze_estimation.utils.geometry import rotation_matrix_to_euler

    estimator, _, _ = _estimator()
    pose = estimator._solve_pnp(_mesh_for_pose(np.array([0.0, 0.3, 0.0]), np.array([0.0, 0, 600])))

    assert pose is not None
    np.testing.assert_allclose(
        pose.euler_angles, rotation_matrix_to_euler(pose.rotation_matrix), atol=1e-9
    )


def test_previous_solution_is_cached_as_the_next_guess():
    estimator, _, _ = _estimator()
    mesh = _mesh_for_pose(np.zeros(3), np.array([0.0, 0.0, 600.0]))
    assert estimator._prev_rvec is None

    estimator._solve_pnp(mesh)
    first_rvec = estimator._prev_rvec.copy()

    estimator._solve_pnp(mesh)

    # Re-solving from the guess refines it slightly rather than changing it.
    np.testing.assert_allclose(estimator._prev_rvec, first_rvec, atol=1e-6)


def test_ransac_solver_recovers_a_pose():
    estimator, _, _ = _estimator(use_ransac=True)

    pose = estimator._solve_pnp(_mesh_for_pose(np.zeros(3), np.array([0.0, 0.0, 600.0])))

    assert pose is not None
    np.testing.assert_allclose(pose.tvec, [0.0, 0.0, 600.0], atol=2.0)


def test_ransac_rejects_an_outlier_landmark():
    """One corrupted landmark must not drag the pose off (the reason for RANSAC)."""
    estimator, _, _ = _estimator(use_ransac=True)
    mesh = _mesh_for_pose(np.zeros(3), np.array([0.0, 0.0, 600.0]))
    mesh[LANDMARK_INDICES[1]] += np.array([90.0, 90.0], dtype=np.float32)  # chin

    pose = estimator._solve_pnp(mesh)

    assert pose is not None
    np.testing.assert_allclose(pose.tvec, [0.0, 0.0, 600.0], atol=8.0)


# ── Failure paths ─────────────────────────────────────────────────────────────


def test_solver_failure_returns_none(monkeypatch):
    estimator, _, _ = _estimator()
    monkeypatch.setattr(cv2, "solvePnP", lambda *a, **k: (False, None, None))

    assert estimator._solve_pnp(_mesh_for_pose(np.zeros(3), np.array([0, 0, 600]))) is None


def test_opencv_error_is_swallowed(monkeypatch):
    """A degenerate mesh makes cv2 raise; the stage must drop the frame, not die."""
    estimator, _, _ = _estimator()

    def _boom(*args, **kwargs):
        raise cv2.error("intentional failure")

    monkeypatch.setattr(cv2, "solvePnP", _boom)

    assert estimator._solve_pnp(np.zeros((468, 2), dtype=np.float32)) is None


def test_a_failed_solve_does_not_poison_the_cached_guess(monkeypatch):
    estimator, _, _ = _estimator()
    monkeypatch.setattr(cv2, "solvePnP", lambda *a, **k: (False, None, None))

    estimator._solve_pnp(np.zeros((468, 2), dtype=np.float32))

    assert estimator._prev_rvec is None
    assert estimator._prev_tvec is None


# ── set_camera_intrinsics ─────────────────────────────────────────────────────


def test_set_camera_intrinsics_updates_the_matrices():
    estimator, _, _ = _estimator()
    new_cam = CAM * 1.5
    new_dist = np.array([0.1, 0.0, 0.0, 0.0, 0.0])

    estimator.set_camera_intrinsics(new_cam, new_dist)

    np.testing.assert_allclose(estimator._camera_matrix, new_cam)
    np.testing.assert_allclose(estimator._dist_coeffs, new_dist)


def test_set_camera_intrinsics_discards_the_stale_extrinsic_guess():
    """A cached pose from the old intrinsics is worse than no guess at all."""
    estimator, _, _ = _estimator()
    estimator._solve_pnp(_mesh_for_pose(np.zeros(3), np.array([0.0, 0.0, 600.0])))
    assert estimator._prev_rvec is not None

    estimator.set_camera_intrinsics(CAM, DIST)

    assert estimator._prev_rvec is None
    assert estimator._prev_tvec is None


# ── process() ─────────────────────────────────────────────────────────────────


def test_process_ignores_a_packet_of_the_wrong_type():
    estimator, _, q_out = _estimator()

    estimator.process("not a mesh packet")

    assert q_out.qsize() == 0


def test_process_emits_a_pose_for_a_valid_mesh():
    estimator, _, q_out = _estimator()

    estimator.process(_mesh_packet(_mesh_for_pose(np.zeros(3), np.array([0, 0, 600]))))

    packet = q_out.get_nowait()
    assert packet.head_pose is not None
    np.testing.assert_allclose(packet.head_pose.tvec, [0.0, 0.0, 600.0], atol=1.0)
    assert packet.confidence == pytest.approx(0.9)


def test_process_relays_iris_and_frame_data_unchanged():
    estimator, _, q_out = _estimator()

    estimator.process(_mesh_packet(_mesh_for_pose(np.zeros(3), np.array([0, 0, 600]))))

    packet = q_out.get_nowait()
    assert packet.frame is FRAME
    assert packet.left_iris_center == (280.0, 240.0)
    assert packet.right_iris_center == (360.0, 240.0)
    assert packet.left_iris_radius == 8.0
    assert packet.right_iris_radius == 8.0


def test_process_reports_zero_confidence_and_no_pose_for_a_low_confidence_mesh():
    estimator, _, q_out = _estimator()

    estimator.process(
        _mesh_packet(_mesh_for_pose(np.zeros(3), np.array([0, 0, 600])), confidence=0.0)
    )

    packet = q_out.get_nowait()
    assert packet.head_pose is None
    assert packet.confidence == 0.0


def test_process_skips_a_truncated_mesh():
    estimator, _, q_out = _estimator()
    short_mesh = np.zeros((100, 2), dtype=np.float32)

    estimator.process(_mesh_packet(short_mesh))

    packet = q_out.get_nowait()
    assert packet.head_pose is None
    assert packet.confidence == 0.0


def test_unknown_solvepnp_method_degrades_at_construction(caplog):
    with caplog.at_level(logging.WARNING, logger="gaze_estimation.pose.head_pose"):
        estimator, _, _ = _estimator(solvepnp_method="SOLVEPNP_NOPE")

    assert estimator._flags == cv2.SOLVEPNP_ITERATIVE
    assert "Unknown solvepnp method" in caplog.text


def test_rotation_to_euler_helper_matches_the_solver():
    estimator, _, _ = _estimator()
    rot_vector = np.array([0.0, 0.25, 0.0])

    euler = estimator.rotation_to_euler(rot_vector)

    rotation, _ = cv2.Rodrigues(rot_vector)
    from gaze_estimation.utils.geometry import rotation_matrix_to_euler

    np.testing.assert_allclose(euler, rotation_matrix_to_euler(rotation), atol=1e-9)


def test_process_carries_the_face_box_forward():
    """The gaze feature extractor needs the box, and only this stage holds it."""
    estimator, _, q_out = _estimator()

    estimator.process(_mesh_packet(_mesh_for_pose(np.zeros(3), np.array([0.0, 0.0, 600.0]))))

    assert q_out.get_nowait().face_bbox == (100, 100, 200, 200)


# ── Mesh → pose → gaze chain ──────────────────────────────────────────────────


def test_mesh_packet_survives_the_whole_chain():
    """Regression: PosePacket had no ``face_bbox``, so the gaze stage raised

    ``AttributeError`` on every frame.  StageThread logged and dropped the item,
    so the pipeline produced no features at all while appearing healthy.
    """
    from gaze_estimation.gaze.gaze_geometry import GazeGeometryEstimator

    pose_estimator, _, pose_out = _estimator()
    gaze_out: queue.Queue = queue.Queue()
    gaze_estimator = GazeGeometryEstimator(
        pose_out, gaze_out, threading.Event(), camera_matrix=CAM, dist_coeffs=DIST
    )

    pose_estimator.process(_mesh_packet(_mesh_for_pose(np.zeros(3), np.array([0.0, 0.0, 600.0]))))
    gaze_estimator.process(pose_out.get_nowait())

    gaze_packet = gaze_out.get_nowait()
    assert gaze_packet.head_pose is not None
    assert gaze_packet.gaze_ray_left is not None
    assert gaze_packet.gaze_ray_right is not None
    # The face-box features prove the box made it across the seam.
    assert gaze_packet.features["face_x"] == pytest.approx(100.0 / 640.0)
    assert gaze_packet.features["face_width"] == pytest.approx(200.0 / 640.0)


def test_chain_started_from_a_low_confidence_mesh_still_emits_a_gaze_packet():
    from gaze_estimation.gaze.gaze_geometry import GazeGeometryEstimator

    pose_estimator, _, pose_out = _estimator()
    gaze_out: queue.Queue = queue.Queue()
    gaze_estimator = GazeGeometryEstimator(
        pose_out, gaze_out, threading.Event(), camera_matrix=CAM, dist_coeffs=DIST
    )
    mesh = _mesh_for_pose(np.zeros(3), np.array([0.0, 0.0, 600.0]))

    pose_estimator.process(_mesh_packet(mesh, confidence=0.0))
    gaze_estimator.process(pose_out.get_nowait())

    gaze_packet = gaze_out.get_nowait()
    assert gaze_packet.head_pose is None
    assert gaze_packet.gaze_ray_left is None
    assert gaze_packet.confidence == 0.0
